### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 55: invalid continuation byte

### ISSUE THREAD

**Issue by ilmari-lauhakangas** [qarkai/WelcomeBot#1]
Bot died after observing this quit message: Quit: Odch�z�m

This was the console output:

```
PING :orwell.freenode.net
Traceback (most recent call last):
  File "bot.py", line 328, in <module>
    sys.exit(main())
  File "bot.py", line 318, in main
    msg_recv = msg_handler(ircsock)  # gets message from ircsock
  File "bot.py", line 129, in msg_handler
    new_msg = ircsock.recv(2048).decode('utf-8')  # receive data from the server
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 55: invalid continuation byte
```

**Comment by qarkai** [comment]
Fixed in b10a2b6bf129b7b86cb38f5a3fffcd366e41d1fc
